<a href="https://colab.research.google.com/github/EndlayNavam/Shapeshover_project/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System Specifications

In [ ]:
! pip install pandas

In [ ]:
import numpy as np

In [ ]:
|c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)
print (c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
#create a numpy of ones

In [ ]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of particular value
z=np.full((5,4), 2.3)
print(z)

[[2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3]]


In [ ]:
# create an identity matrix which means same number of rows & columns
#All diagonal elements will be 1
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
#It will only print between 0 and 1 (only float)
b=np.random.random((3,4))
print(b)

[[0.93069529 0.86422065 0.35984872 0.03375603]
 [0.91604946 0.767824   0.42696656 0.39191832]
 [0.93346308 0.3685825  0.62360395 0.33172178]]


In [ ]:
#create a numpy array with random integers of our choice
c= np.random.randint(10,100,(3,5))
print(c)

[[50 87 98 42 82]
 [49 83 44 29 88]
 [98 36 89 97 81]]


In [ ]:
# array of evenly spaced values (starting point, ending point, number of values)
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values (starting point, ending point, step between each number)
#Last number not counted
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert list to numpy array
list1 = [1,2,3]

np_array = np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3]


numpy.ndarray

Analysis of numpy array

In [ ]:
c = np.random.randint(10,100,(5,5))
print(c)

[[10 87 18 22 44]
 [38 54 53 75 26]
 [42 14 17 22 50]
 [77 45 14 23 16]
 [34 27 19 86 83]]


In [ ]:
#array dimension
print (c.shape)

#number of dimensions
print(c.ndim)

#number of elements in an array
print(c.size)

# datatype of value
print(c.dtype)

(5, 5)
2
25
int64


Mathematical Operations

In [ ]:
list1= [1,2,3,4,5]
list2 = [6,7,8,9,10]
print (list1+list2)

a= np.random.randint(0,10,(3,3))
b= np.random.randint(0,10,(3,3))
print(a)

print(b)

print(a+b)
print(np.add(a,b))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[5 3 4]
 [2 3 7]
 [1 3 9]]
[[1 0 3]
 [6 6 4]
 [4 0 9]]
[[ 6  3  7]
 [ 8  9 11]
 [ 5  3 18]]
[[ 6  3  7]
 [ 8  9 11]
 [ 5  3 18]]
